name: AWS Resource Creation 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Deploy_CFT:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload Script to S3 Bucket
        run: |
          aws s3 cp Products_glue_Job.py s3://finalprojectinput/github/products/
          aws s3 cp Sales.py s3://finalprojectinput/github/sales/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --stack-name CFTStack \
            --template-file .github/workflows/automate.yml \
            --capabilities CAPABILITY_IAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}




          
