name: AWS Resource Creation 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Deploy_CFT:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload Script to S3 Bucket
        run: |
          aws s3 cp Products_Glue_Job.py dim_product.csv s3://finalprojectinput/From Github/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
